version: '3.9'

services:
#  fastapi_app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: fastapi_app
#    ports:
#      - "8000:8000"
#    networks:
#      - cii_app_network
#    environment:
#      - ELASTICSEARCH_HOST=http://elasticsearch:9200
#    depends_on:
#      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - cii_app_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - cii_app_network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

networks:
  cii_app_network:
    driver: bridge

volumes:
  es_data:
    driver: local
